# Generated by Django 4.2.9 on 2024-01-11 09:56

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0002_alter_duties_crop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duties',
            old_name='crop_id',
            new_name='crop',
        ),
        migrations.AddField(
            model_name='duties',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='duties',
            table='duties',
        ),
    ]
